<?=$this->placeholder('header')->set($this->translate('An Error Occured'));?>
<h2><?php echo $this->message ?></h2>

<?php if (isset($this->exception)): ?>
<h3><?=$this->translate('Exception information');?></h3>
<?php if ($this->exception->getMessage()) :?>
<p>
    <b><?=$this->translate('Message');?>:</b> <?php echo $this->exception->getMessage() ?>
</p>
<?php endif;?>

<h3>Stack trace</h3>
<pre style="overflow: auto; padding: 0 0 15px 0;"><?php echo $this->exception->getTraceAsString() ?></pre>

<h3>Request Parameters</h3>
<pre><?php echo var_export($this->request->getParams(), true) ?></pre>
<?php endif ?>